version: '3.9'

services:
  php-env:
    build: .
    volumes:
      - ./oxyproject:/var/www/html
    ports:
      - '8000:80'

  mysql-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
